# Generated by Django 5.1.5 on 2025-01-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('avg_salary', models.FloatField(verbose_name='Средняя зарплата')),
                ('vacancies_share', models.FloatField(verbose_name='Доля вакансий (%)')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название профессии')),
                ('description', models.TextField(verbose_name='Описание профессии')),
                ('image', models.ImageField(upload_to='profession_images/', verbose_name='Изображение профессии')),
            ],
        ),
        migrations.CreateModel(
            name='RecentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('salary', models.CharField(max_length=100, verbose_name='Оклад')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('skill_name', models.CharField(max_length=200, verbose_name='Навык')),
                ('frequency', models.IntegerField(verbose_name='Частота использования')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('avg_salary', models.FloatField(verbose_name='Средняя зарплата')),
                ('num_vacancies', models.IntegerField(verbose_name='Количество вакансий')),
            ],
        ),
    ]
