# Generated by Django 5.1.5 on 2025-01-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Оклад'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profession_images/', verbose_name='Изображение профессии'),
        ),
    ]
